default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: youtube_playlist_v1d_development
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>

test:
  <<: *default
  database: youtube_playlist_v1d_test
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>